package ru.atkachev.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-07T18:10:05.213+03:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.atkachev.ru/", name = "ProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/createProjectRequest", output = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/createProjectResponse")
    @RequestWrapper(localName = "createProject", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.CreateProjectResponse")
    public void createProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/getProjectListRequest", output = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/getProjectListResponse")
    @RequestWrapper(localName = "getProjectList", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.GetProjectList")
    @ResponseWrapper(localName = "getProjectListResponse", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.GetProjectListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.atkachev.tm.endpoint.Project> getProjectList();

    @WebMethod
    @Action(input = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/deleteProjectRequest", output = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/deleteProjectResponse")
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.DeleteProjectResponse")
    public void deleteProject(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/updateProjectRequest", output = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/updateProjectResponse")
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.UpdateProjectResponse")
    public void updateProject(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/setProjectListRequest", output = "http://endpoint.tm.atkachev.ru/ProjectEndpoint/setProjectListResponse")
    @RequestWrapper(localName = "setProjectList", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.SetProjectList")
    @ResponseWrapper(localName = "setProjectListResponse", targetNamespace = "http://endpoint.tm.atkachev.ru/", className = "ru.atkachev.tm.endpoint.SetProjectListResponse")
    public void setProjectList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<ru.atkachev.tm.endpoint.Project> arg0
    );
}
